<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.9</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>com.shift</groupId>
	<artifactId>akrpc</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>akrpc</name>
	<description>AK-RPC framework</description>
	<packaging>pom</packaging>

	<url>https://github.com/hgkmail/akrpc</url>
	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://mit-license.org/</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>kimhuang</name>
			<email>hgkformap@gmail.com</email>
			<url>https://github.com/hgkmail</url>
		</developer>
	</developers>
	<scm>
		<url>https://github.com/hgkmail/akrpc</url>
	</scm>

	<properties>
		<java.version>21</java.version>
		<akrpc.version>0.0.1-SNAPSHOT</akrpc.version>
		<spring-boot.version>3.5.9</spring-boot.version>
		<lombok.version>1.18.40</lombok.version>
		<apache.commons-lang3.version>3.18.0</apache.commons-lang3.version>
		<apache.commons-collections4.version>4.5.0</apache.commons-collections4.version>
		<guava.version>33.4.0-jre</guava.version>
		<consul-api.version>1.4.5</consul-api.version>
		<msgpack.version>0.9.10</msgpack.version>
		<kryo.version>5.6.2</kryo.version>
		<hessian.version>4.0.66</hessian.version>
	</properties>

	<modules>
		<module>akrpc-common</module>
		<module>akrpc-provider</module>
		<module>akrpc-consumer</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-web</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-test</artifactId>
				<version>${spring-boot.version}</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>com.shift</groupId>
				<artifactId>akrpc-common</artifactId>
				<version>${akrpc.version}</version>
			</dependency>
			<dependency>
				<groupId>com.shift</groupId>
				<artifactId>akrpc-provider</artifactId>
				<version>${akrpc.version}</version>
			</dependency>
			<dependency>
				<groupId>com.shift</groupId>
				<artifactId>akrpc-consumer</artifactId>
				<version>${akrpc.version}</version>
			</dependency>

			<!--常用工具类 -->
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${apache.commons-lang3.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-collections4</artifactId>
				<version>${apache.commons-collections4.version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-actuator</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-aop</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>

			<dependency>
				<groupId>com.ecwid.consul</groupId>
				<artifactId>consul-api</artifactId>
				<version>${consul-api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>${guava.version}</version>
			</dependency>
			<dependency>
				<groupId>org.msgpack</groupId>
				<artifactId>jackson-dataformat-msgpack</artifactId>
				<version>${msgpack.version}</version>
			</dependency>
			<dependency>
				<groupId>com.esotericsoftware</groupId>
				<artifactId>kryo</artifactId>
				<version>${kryo.version}</version>
			</dependency>
			<dependency>
				<groupId>com.caucho</groupId>
				<artifactId>hessian</artifactId>
				<version>${hessian.version}</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
						<path>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-configuration-processor</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>central</id>
			<name>central</name>
			<url>https://repo1.maven.org/maven2</url>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>

		<!-- 阿里云maven仓库 -->
		<repository>
			<id>aliyun</id>
			<name>aliyun nexus</name>
			<url>https://maven.aliyun.com/repository/public</url>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>public</id>
			<name>aliyun nexus</name>
			<url>https://maven.aliyun.com/repository/public</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
