spring:
  application:
    name: akrpc-provider

server:
  port: 8081

akrpc:
  discovery:
    type: zookeeper
    address: localhost:2181
#    type: consul
#    address: localhost:8500

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans