spring:
  application:
    name: akrpc-consumer

server:
  port: 8082

akrpc:
  consumer:
    provider-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans