spring:
  application:
    name: akrpc-consumer

server:
  port: 8082

akrpc:
  consumer:
    read-timeout: 3000
    connect-timeout: 1000
    retries: 3
    encode: msgpack
    gzip: true
  discovery:
    type: consul
    address: localhost:8500

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans